lib/luks-functions: - added unlock_volume() capture_outputs()                     - a lot of code cleanup, ready for release

diff --git a/lib/luks-functions b/lib/luks-functions
--- a/lib/luks-functions
+++ b/lib/luks-functions
@@ -1,12 +1,12 @@
 # -*- mode: sh -*-
-# Version 0.1 Copyright (c) Magnus (Mem) Sandberg 2020
+# Version 1.0 Copyright (c) Magnus (Mem) Sandberg 2020
 # Email: mem (a) datakon , se
 #
 # Created by Mem, 2020-05-06
 
 # Version control of this file
 LUKS_FUNCTIONS_MAJOR="1"
-LUKS_FUNCTIONS_MINOR="3"
+LUKS_FUNCTIONS_MINOR="4"
 
 ## Maybe useful functions
 #info () {
@@ -23,7 +23,7 @@ LUKS_FUNCTIONS_MINOR="3"
 #    echo >2 $*
 #}
 
-# Used by volume_info(), disk_free()
+# Used by luksextend.sh, volume_info(), disk_free()
 int_to_human () {
     # Convert integer number to human readable
     #
@@ -35,19 +35,20 @@ int_to_human () {
     # human readable value
     local dec=""
     local int="$1"
+    local format="$2"
 
     # Return to caller if not an integer
     [[ "$int" =~ ^[0-9]+$ ]] || return $?
 
-    if [ "$(( ${int}/1024*1024 ))" -eq ${int} ] ; then
+    if [ "$(( ${int} / 1024 * 1024 ))" -eq ${int} ] || [ "xKiB" = "x${format}" ] ; then
 	for unit in B K M G T P E Z Y; do
             if [ $int -lt 1024 ] || [ "$unit" = "Y" ] ; then
 		[ "$dec" = ".00" ] && dec=""
 		echo "${int}${dec}${unit}"
 		break
             fi
-	    printf -v dec ".%02d" $((int % 1024 * 100 / 1024))
-            int=$((int/1024))
+	    printf -v dec ".%02d" $(( ${int} % 1024 * 100 / 1024 ))
+            int=$(( ${int} / 1024 ))
 	done
     else
 	for unit in B kB MB GB TB PB EB ZB YB; do
@@ -56,8 +57,8 @@ int_to_human () {
 		echo "${int}${dec}${unit}"
 		break
             fi
-	    printf -v dec ".%02d" $((int % 1000 * 100 / 1000))
-            int=$((int/1000))
+	    printf -v dec ".%02d" $(( ${int} % 1000 * 100 / 1000 ))
+            int=$(( ${int} / 1000 ))
 	done
     fi
 }
@@ -127,13 +128,13 @@ calc_newsize () {
 	newsize=$( echo $newsize | sed -e 's/%$//' )
 	if [[ "$newsize" =~ ^[+] ]] ; then
 	    newsize=$( echo $newsize | sed -e 's/^+//' )
-	    newsize=$((newsize+100))
+	    newsize=$(( ${newsize} + 100 ))
 	fi
 	if [ $newsize -le 100 ] ; then
 	    echo "Size value too small: $addsize."
 	    return 2
 	fi
-	newsize=$((cursize*newsize/100))
+	newsize=$(( ${cursize} * ${newsize} / 100 ))
     elif [[ "$newsize" =~ ^[+]?[0-9]+[cBwb]$ ]] || [[ "$newsize" =~ ^[+]?[0-9]+[.0-9]?[0-9]*[KMGTPEZY](iB)?$ ]] || [[ "$newsize" =~ ^[+]?[0-9]+[.0-9]?[0-9]*[kKMGTPEZY]B$ ]] ; then
 	if [[ "$newsize" =~ ^[+] ]] ; then
 	    newsize=$( echo $newsize | sed -e 's/^+//' )
@@ -142,7 +143,7 @@ calc_newsize () {
 		echo "$newsize"
 		return $RC
 	    fi
-	    newsize=$((cursize+newsize))
+	    newsize=$(( ${cursize} + ${newsize} ))
 	else
 	    newsize=$( human_to_number "${newsize}" ) ; RC=$?
 	    if [ $RC -gt 0 ] ; then
@@ -176,31 +177,10 @@ disk_free () {
     #     free-num           : free disk space (non-superuser) in numeric value
     #     free-human         : free disk space (non-superuser) converted to human readable format
     local volpath="$1"
+    local numberformat="$2"
 
     local free="$(( $(stat -f -c '%a*%s' -- ${volpath}/.) ))"
-    local freehuman=$( int_to_human $free )
-    echo "${free}:${freehuman}"
-    return 0
-}
-
-# not used for now
-disk_needed () {
-    # Free disk space
-    #
-    # Return codes:
-    # >0: ?
-    #  0: all okay
-    #
-    # Return string:
-    # information string, colon separated values
-    #   format: <free-num>:<free-human>
-    #     free-num           : free disk space (non-superuser) in numeric value
-    #     free-human         : free disk space (non-superuser) converted to human readable format
-    local R="" ; local RC=""
-    local volpath="$1"
-
-    local free="$(( $(stat -f -c '%a*%s' -- ${volpath}/.) ))"
-    local freehuman=$( int_to_human $free )
+    local freehuman=$( int_to_human $free $numberformat )
     echo "${free}:${freehuman}"
     return 0
 }
@@ -287,9 +267,9 @@ volume_info () {
     local used_space="$(( ${used_blocks}*${block_size} ))"
     [ ${used_space} -lt ${file_size} ] && sparse=1 || sparse=0
     [ "$(( ${file_size}/1024*1024 ))" -eq ${file_size} ] && type="KiB" || type="B"
-    local filehuman=$( int_to_human $file_size )
-    local usedhuman=$( int_to_human $used_space )
-    local diskfree=$( disk_free ${volpath} )
+    local filehuman=$( int_to_human $file_size $type )
+    local usedhuman=$( int_to_human $used_space $type )
+    local diskfree=$( disk_free ${volpath} $type )
     echo "${sparse}:${file_size}:${filehuman}:${type}:${used_space}:${usedhuman}:${diskfree}"
     return 0
 }
@@ -397,6 +377,64 @@ check_if_unlocked () {
 }
 
 # Used by luksextend.sh
+unlock_volume () {
+    # Unlock LUKS volume
+    #
+    # Return codes:
+    # >0: some udisksctl problem
+    #  0: volume locked
+    #
+    # Return string:
+    # nothing or error message from udisksctl
+    local Ru="" ; local Eu="" ; local RC=""
+    local resp="";
+    local returnvar="$1"
+    local luksdev="$2"
+
+    Ru=$( check_if_unlocked "${luksdev}" ) ; RC=$?
+    if [ $RC -gt 0 ] ; then
+	do_yubikey resp ; RC=$?
+	if [ $RC -eq 2 ] || [ $RC -eq 3 ]; then
+	    echo "No configured YubiKey (slot ${YKSLOT}) found."
+	    read -p "Continue without YubiKey (y/N): " Ru
+	    case $Ru in
+		y|Y|[yY][eE][sS])
+		    echo
+		    echo "No configured YubiKey (slot ${YKSLOT}) found, will use static passphrase."
+		    capture_outputs Ru Eu udisksctl unlock -b $luksdev ; RC=$?
+		    if [ $RC -gt 0 ] ; then
+			printf -v "$returnvar" '%s' "Could not unlock volume, maybe wrong passphrase."
+			return $RC
+		    fi
+		    fsdev=$( echo $Ru | sed -e 's/.* as //' | sed -e 's/\.$//' )
+		    ;;
+		*)
+		    do_yubikey resp ; RC=$?
+		    if [ $RC -gt 0 ] ; then
+			printf -v "$returnvar" '%s' "${resp}."
+			return $RC
+		    fi
+		    echo "Unlock of $luksdev will take a number of seconds, standby..."
+		    # https://unix.stackexchange.com/questions/447615/provide-password-to-udisks-to-unlock-luks-encrypted-device
+		    Ru=$( udisksctl unlock -b $luksdev --key-file <( echo -n "$resp" ) ) ; RC=$?
+		    fsdev=$( echo $Ru | sed -e 's/.* as //' | sed -e 's/\.$//' )
+		    ;;
+	    esac
+	else
+	    echo "Unlock of $luksdev will take a number of seconds, standby..."
+	    # https://unix.stackexchange.com/questions/447615/provide-password-to-udisks-to-unlock-luks-encrypted-device
+	    Ru=$( udisksctl unlock -b $luksdev --key-file <( echo -n "$resp" ) ) ; RC=$?
+	    fsdev=$( echo $Ru | sed -e 's/.* as //' | sed -e 's/\.$//' )
+	fi
+    else
+	fsdev="$Ru"
+	[ $DEBUG -gt 0 ] && echo "LUKS volume already unlocked."
+    fi
+    printf -v "$returnvar" '%s' "${fsdev}"
+    return 0
+}
+
+# Used by luksextend.sh
 lock_volume () {
     # Lock LUKS volume
     #
@@ -474,34 +512,77 @@ concept_volume_info () {
     echo 'For the moment used size: "Block size" * "Block count" + "Data segment offset"'
 }
 
+# Used by do_yubikey()
+capture_outputs () {
+    # This doesn't work with interactive commands as regular prompts or requests for
+    # input uses STDERR for prompting.
+    #
+    # The following is very Bash specific and has its flaws;
+    # - outputs longer that 1008 bytes may not be catched correctly due to buffer sizes
+    # - the use of 'eval' is always risky, can execute variables as code, etc
+
+    # https://stackoverflow.com/questions/11027679/capture-stdout-and-stderr-into-different-variables/11027843#11027843
+    # referenced from https://stackoverflow.com/questions/13806626/capture-both-stdout-and-stderr-in-bash
+    #
+    # other useful
+    # https://stackoverflow.com/questions/3130375/bash-script-store-stderr-in-a-variable
+    # https://stackoverflow.com/questions/962255/how-to-store-standard-error-in-a-variable
+    # (with a lot of interesting examples)
+    # and maybe also https://stackoverflow.com/questions/32890389/can-you-redirect-stderr-for-an-entire-bash-session
+
+    local resp="$1" ; local error="$2" ; shift 2
+    local t_std="" ; local t_err="" ; local t_ret=0
+
+    eval "$( eval "$@" \
+        2> >(t_err=$(cat); declare -p t_err) \
+         > >(t_std=$(cat); declare -p t_std); \
+             t_ret=$?; declare -p t_ret )"
+
+    printf -v "$resp" '%s' "$t_std"
+    printf -v "$error" '%s' "$t_err"
+    return $t_ret
+}
+
 # Used by luksextend.sh
 do_yubikey () {
-    read -s -p "Enter challenge: " pph ; echo
-    [ $HASH -gt 0 ] && pph=$(printf %s "$pph" | sha256sum | awk '{print $1}')
-    echo "Sending challenge to YubiKey, press button if blinking."
-    Resp="$( ykchalresp -${YKSLOT} "$pph" || true )"
-    if [ -z "$Resp" ] ; then
-	unset pph ; unset Resp
-	echo "Yubikey not available, wrong config (slot ${YKSLOT}) or timed out waiting for button press."
-	exit 1
-    fi
-    [ $CONCATENATE -gt 0 ] ; Resp=$pph$Resp
-    echo "Unlock of $luksdev will take a number of seconds, standby..."
-    [ $DEBUG -gt 0 ] && echo "Sleep before socat unlocks $loopdev: ${SLEEPBEFORE}."
-    [ $DEBUG -gt 0 ] && echo "Sleep adter socat unlocked $loopdev: ${SLEEPAFTER}."
-    R=$( (sleep ${SLEEPBEFORE}; echo "$Resp"; sleep ${SLEEPAFTER}) | socat - EXEC:"udisksctl unlock -b $luksdev",pty,setsid,ctty ) ; RC=$?
-    unset pph ; unset Resp
-    R=$( echo $R | sed -e 's/\r$//' ) # as socat adds trailing <CR>
-    [ $DEBUG -gt 0 ] && echo "\$R: '$R'"
-    if [ "$R" = "Passphrase: " ] ; then
-	echo
-	echo "Passphrase prompt as response from unlock."
-	echo "Variable \$SLEEPAFTER probably has to be increased in $CONFIG."
-	echo
-	if [ $PHYSDEV -eq 0 ] ; then
-	    echo "Tear down loop device."
-	    udisksctl loop-delete -b $loopdev
+    # Handle challange-response for YubiKey
+    #
+    # Return codes:
+    #  3: YubiKey missing
+    #  2: YubiKey slot not configured
+    #  1: Error from YubiKey command
+    #  0: response stored in return variable
+    #
+    # Return string:
+    # challenge-response string or error message
+    local Ry="" ; local Ey="" ; local RC=""
+    local pph=""
+    local returnvar="$1"
+
+    capture_outputs Ry Ey ykinfo -q -${YKSLOT} ; RC=$?
+    if [ $RC -eq 0 ] && [ $Ry -eq 1 ]; then
+	[ $DEBUG -gt 0 ] && echo "Found attached YubiKey, will try challenge-response."
+
+	read -s -p "Enter YubiKey challenge: " pph ; echo
+	[ $HASH -gt 0 ] && pph=$(printf %s "$pph" | sha256sum | awk '{print $1}')
+	echo "Sending challenge to YubiKey, press button if blinking."
+	capture_outputs Ry Ey ykchalresp -${YKSLOT} "$pph" ; RC=$?
+	if [ $RC -gt 0 ] ; then
+	    unset pph ; unset Ry
+	    printf -v "$returnvar" '%s' "Maybe missing or wrong config (slot ${YKSLOT}): ${Ey}."
+	    return 1
 	fi
-	exit 1
+	[ $CONCATENATE -gt 0 ] ; Ry=$pph$Ry
+	# about dynamic/pointer variables, including "Risks" section
+	# see https://stackoverflow.com/questions/16553089/dynamic-variable-names-in-bash
+	printf -v "$returnvar" '%s' "${Ry}"
+	unset pph ; unset Ry
+	return 0
+    elif [ $RC -eq 0 ] && [ $Ry -eq 0 ]; then
+	printf -v "$returnvar" '%s' "YubiKey found but slot ${YKSLOT} not configured."
+	return 2
+    else
+	printf -v "$returnvar" '%s' "${Ey}."
+	return 3
     fi
 }
